server:
  servlet:
    application-display-name: euraka-server
    context-path: /eureka/server/
  port: 8761

spring:
  application:
    name: euraka-server
  config:
    location: http://localhost:8088
    
eureka:
  client:
      service-url:
          defaultZone: http://localhost:8761/eureka/