server:
  servlet:
    application-display-name: euraka-server
  port: 8761

spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: euraka-server
    
eureka:
  client:
      service-url:
          defaultZone: http://localhost:8761/eureka/